### ISSUE TITLE
Code building failed

### ISSUE THREAD

**Issue by carloflore** [MapCollaboration/MontBlanc#5]
Dear all,

I am trying to install MontBlanc on my laptop. I already have installed NangaParbat with all its dependencies.

During the compilation of the code, I get the two following errors:

`/home/charlie/research/MontBlanc/run/ComputeChi2s.cc: In function ‘void compute_chi2s(std::string, int, std::string, std::string)’:
/home/charlie/research/MontBlanc/run/ComputeChi2s.cc:166:85: error: no matching function for call to ‘NangaParbat::CutFactory::GetInstance(NangaParbat::DataHandler&, std::__cxx11::basic_string<char>, double, double, std::vector<double>)’
  166 |            (c["pars"] ? c["pars"].as<std::vector<double>>() : std::vector<double>{})));
      |                                                                                     ^
In file included from /home/charlie/research/MontBlanc/run/ComputeChi2s.cc:11:
/usr/local/include/NangaParbat/cutfactory.h:17:33: note: candidate: ‘static std::shared_ptr<NangaParbat::Cut> NangaParbat::CutFactory::GetInstance(const NangaParbat::DataHandler&, const string&, const double&, const double&)’
   17 |     static std::shared_ptr<Cut> GetInstance(DataHandler const& dataset, std::string const& name, double const& min, double const& max);
      |                                 ^~~~~~~~~~~
/usr/local/include/NangaParbat/cutfactory.h:17:33: note:   candidate expects 4 arguments, 5 provided
`

and

`/home/charlie/research/MontBlanc/run/Optimize.cc: In function ‘int main(int, char**)’:
/home/charlie/research/MontBlanc/run/Optimize.cc:161:85: error: no matching function for call to ‘NangaParbat::CutFactory::GetInstance(NangaParbat::DataHandler&, std::__cxx11::basic_string<char>, double, double, std::vector<double>)’
  161 |            (c["pars"] ? c["pars"].as<std::vector<double>>() : std::vector<double>{})));
      |                                                                                     ^
In file included from /home/charlie/research/MontBlanc/run/Optimize.cc:19:
/usr/local/include/NangaParbat/cutfactory.h:17:33: note: candidate: ‘static std::shared_ptr<NangaParbat::Cut> NangaParbat::CutFactory::GetInstance(const NangaParbat::DataHandler&, const string&, const double&, const double&)’
   17 |     static std::shared_ptr<Cut> GetInstance(DataHandler const& dataset, std::string const& name, double const& min, double const& max);
      |                                 ^~~~~~~~~~~
/usr/local/include/NangaParbat/cutfactory.h:17:33: note:   candidate expects 4 arguments, 5 provided
`

They both point to the same function `GetInstance` and come from the cut class of NangaParbat.

Is there any problem on my side? Or am I missing some updated version of `cutfactory.h` that is not available here on github?

Best,

Carlo

**Comment by vbertone** [comment]
Hi Carlo,

thanks for reporting this problem.
I think I know where this comes from: it is essentially the fact that the public version of `NangaParbat` and `MontBlanc` are not synchronised. As a matter of fact, there exists a private version on `NangaParbat`, called `NangaParbat-Beta`, that we use for developments but that is the real "alive" version of the code.

I've just sent you an invite that should allow you to download the code. Once you've installed that version, also the master of `MontBlanc` should compile. If this is not the case or you have any further problems just let me know.

Cheers,
Valerio

**Comment by carloflore** [comment]
Hi Valerio,

thanks, with the beta version it all works!

Cheers,

Carlo
